package br.com.axecloud.app.feature.store
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.*
import androidx.compose.ui.graphics.*
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.*
import androidx.hilt.navigation.compose.hiltViewModel
import br.com.axecloud.app.designsystem.theme.AxeCloudThemeTokens
import br.com.axecloud.app.feature.home.asMoney
import coil.compose.AsyncImage
private val StorePlum=Color(0xFF43233D);private val StorePeach=Color(0xFFF3A96F);private val StoreCream=Color(0xFFFFF1E2)
@Composable fun StoreRoute(vm:StoreViewModel= hiltViewModel()){val s by vm.state.collectAsState();val snack=remember{SnackbarHostState()};LaunchedEffect(s.message){s.message?.let{snack.showSnackbar(it);vm.consume()}};StoreScreen(s,snack,vm)}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun StoreScreen(s:StoreUiState,snack:SnackbarHostState,vm:StoreViewModel){var remove by remember{mutableStateOf<StoreProduct?>(null)};Scaffold(containerColor=AxeCloudThemeTokens.Canvas,snackbarHost={SnackbarHost(snack)},floatingActionButton={if(s.isFilho&&s.cartCount>0)ExtendedFloatingActionButton({vm.cart(true)},containerColor=StorePlum,contentColor=Color.White){Icon(Icons.Outlined.ShoppingBag,null);Spacer(Modifier.width(7.dp));Text("Sacola · ${s.cartCount}")}else if(!s.isFilho)FloatingActionButton({vm.editor()},containerColor=StorePeach,contentColor=StorePlum){Icon(Icons.Outlined.Add,"Novo produto")}}){p->LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(17.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){item{StoreHero(s)};item{OutlinedTextField(s.query,vm::query,Modifier.fillMaxWidth(),leadingIcon={Icon(Icons.Outlined.Search,null)},placeholder={Text("Buscar na loja da casa")},singleLine=true,shape=RoundedCornerShape(18.dp))};item{Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){s.categories.forEach{c->FilterChip(s.category==c,{vm.category(c)},label={Text(c)})}}};when{s.loading->item{Box(Modifier.fillMaxWidth().padding(48.dp),contentAlignment=Alignment.Center){CircularProgressIndicator(color=StorePlum)}};s.error!=null&&s.products.isEmpty()->item{Text(s.error,color=MaterialTheme.colorScheme.error)};s.visible.isEmpty()->item{EmptyStore(s.isFilho)};else->itemsIndexed(s.visible,key={_,x->x.id}){i,x->AnimatedVisibility(true,enter=fadeIn()+slideInVertically{22+i*2}){ProductCard(x,s.isFilho,s.cart[x.id]?:0,{vm.add(x)},{vm.editor(x)},{remove=x})}}};if(!s.isFilho&&s.orders.isNotEmpty()){item{Text("PEDIDOS RECENTES",color=StorePlum,fontSize=10.sp,fontWeight=FontWeight.Black,letterSpacing=1.sp,modifier=Modifier.padding(top=8.dp))};items(s.orders,key={"order-${it.id}"}){OrderRow(it)}};item{Spacer(Modifier.height(80.dp))}}};if(s.editorOpen)ProductEditor(s.editor,s.saving,s.error,{vm.editor(open=false)},vm::save);if(s.cartOpen)CartSheet(s,vm);remove?.let{x->AlertDialog(onDismissRequest={remove=null},title={Text("Remover ${x.name}?")},confirmButton={Button({remove=null;vm.delete(x)},colors=ButtonDefaults.buttonColors(containerColor=MaterialTheme.colorScheme.error)){Text("Excluir")}},dismissButton={TextButton({remove=null}){Text("Cancelar")}})}}
@Composable private fun StoreHero(s:StoreUiState)=Surface(shape=RoundedCornerShape(30.dp),color=StorePlum,shadowElevation=8.dp){Box(Modifier.background(Brush.linearGradient(listOf(StorePlum,Color(0xFF71364D))))){Column(Modifier.padding(22.dp)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(46.dp).background(StorePeach,RoundedCornerShape(16.dp)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Storefront,null,tint=StorePlum)};Column(Modifier.padding(start=12.dp)){Text(if(s.isFilho)"VITRINE DA CASA" else "COMÉRCIO DA CASA",color=StorePeach,fontSize=9.sp,fontWeight=FontWeight.Black,letterSpacing=1.sp);Text(if(s.isFilho)"Loja do Axé" else "Gestão da loja",color=Color.White,fontSize=27.sp,fontWeight=FontWeight.Black)}};Spacer(Modifier.height(16.dp));Text(if(s.isFilho)"Reserve itens e cuide do pagamento direto pelo aplicativo." else "${s.products.size} produtos · ${s.products.count{it.stock<=it.minimum}} pedem reposição · ${s.orders.size} pedidos recentes",color=Color.White.copy(.68f),fontSize=11.sp)}}}
@Composable private fun ProductCard(p:StoreProduct,filho:Boolean,cart:Int,add:()->Unit,edit:()->Unit,delete:()->Unit)=Surface(Modifier.fillMaxWidth().clickable(onClick=if(filho)add else edit),shape=RoundedCornerShape(22.dp),color=Color.White,border=BorderStroke(1.dp,AxeCloudThemeTokens.Outline)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(88.dp).clip(RoundedCornerShape(17.dp)).background(StoreCream),contentAlignment=Alignment.Center){if(p.image.isNotBlank())AsyncImage(p.image,p.name,Modifier.fillMaxSize(),contentScale=ContentScale.Crop)else Icon(Icons.Outlined.LocalMall,null,Modifier.size(34.dp),tint=StorePlum)};Column(Modifier.weight(1f).padding(horizontal=12.dp)){Text(p.category.uppercase(),color=Color(0xFFA35C38),fontSize=8.sp,fontWeight=FontWeight.Black);Text(p.name,color=AxeCloudThemeTokens.Ink,fontWeight=FontWeight.Black,maxLines=1,overflow=TextOverflow.Ellipsis);Text(p.description,color=AxeCloudThemeTokens.Muted,fontSize=10.sp,maxLines=2,overflow=TextOverflow.Ellipsis);Text(p.price.asMoney(),color=StorePlum,fontSize=18.sp,fontWeight=FontWeight.Black);Text(if(p.stock>0)"${p.stock} disponíveis" else "Esgotado",color=if(p.stock>0)Color(0xFF4F785D)else MaterialTheme.colorScheme.error,fontSize=9.sp)};if(filho)FilledIconButton(add,enabled=p.stock>cart,colors=IconButtonDefaults.filledIconButtonColors(containerColor=StorePeach,contentColor=StorePlum)){Icon(if(cart>0)Icons.Outlined.AddShoppingCart else Icons.Outlined.Add,null)}else Column{IconButton(edit){Icon(Icons.Outlined.Edit,null)};IconButton(delete){Icon(Icons.Outlined.DeleteOutline,null,tint=AxeCloudThemeTokens.Muted)}}}}
@Composable private fun OrderRow(o:StoreOrder)=Surface(shape=RoundedCornerShape(17.dp),color=Color.White,border=BorderStroke(1.dp,AxeCloudThemeTokens.Outline)){Row(Modifier.fillMaxWidth().padding(13.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Outlined.ReceiptLong,null,tint=StorePlum);Column(Modifier.weight(1f).padding(horizontal=10.dp)){Text(o.childName,color=AxeCloudThemeTokens.Ink,fontWeight=FontWeight.Bold);Text(o.summary,color=AxeCloudThemeTokens.Muted,fontSize=9.sp,maxLines=1)};Text(o.total.asMoney(),color=StorePlum,fontWeight=FontWeight.Black)}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun ProductEditor(p:StoreProduct?,saving:Boolean,error:String?,dismiss:()->Unit,save:(ProductForm)->Unit){var f by rememberSaveable(p?.id){mutableStateOf(p?.let(ProductForm::from)?:ProductForm())};ModalBottomSheet(onDismissRequest=dismiss,containerColor=AxeCloudThemeTokens.Canvas){Column(Modifier.navigationBarsPadding().verticalScroll(rememberScrollState()).padding(horizontal=20.dp).padding(bottom=25.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(if(p==null)"Novo produto" else "Editar produto",color=AxeCloudThemeTokens.Ink,fontSize=25.sp,fontWeight=FontWeight.Black);Field(f.name,{f=f.copy(name=it)},"Nome");Field(f.description,{f=f.copy(description=it)},"Descrição");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Field(f.price,{f=f.copy(price=it)},"Preço",Modifier.weight(1f));Field(f.category,{f=f.copy(category=it)},"Categoria",Modifier.weight(1f))};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Field(f.stock,{f=f.copy(stock=it)},"Estoque",Modifier.weight(1f));Field(f.minimum,{f=f.copy(minimum=it)},"Mínimo",Modifier.weight(1f))};Field(f.image,{f=f.copy(image=it)},"URL da imagem");error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button({save(f)},Modifier.fillMaxWidth().height(52.dp),enabled=!saving&&f.name.isNotBlank(),colors=ButtonDefaults.buttonColors(containerColor=StorePlum)){Text("Salvar na vitrine")}}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun CartSheet(s:StoreUiState,vm:StoreViewModel)=ModalBottomSheet(onDismissRequest={vm.cart(false)},containerColor=AxeCloudThemeTokens.Canvas){Column(Modifier.navigationBarsPadding().padding(horizontal=20.dp).padding(bottom=24.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Minha sacola",color=AxeCloudThemeTokens.Ink,fontSize=25.sp,fontWeight=FontWeight.Black);s.cart.forEach{(id,q)->s.products.find{it.id==id}?.let{p->Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(p.name,fontWeight=FontWeight.Bold);Text((p.price*q).asMoney(),color=StorePlum)};IconButton({vm.quantity(p,-1)}){Icon(Icons.Outlined.Remove,null)};Text(q.toString(),fontWeight=FontWeight.Black);IconButton({vm.quantity(p,1)}){Icon(Icons.Outlined.Add,null)}}}};HorizontalDivider();Row{Text("Total",Modifier.weight(1f),fontWeight=FontWeight.Bold);Text(s.cartTotal.asMoney(),color=StorePlum,fontSize=22.sp,fontWeight=FontWeight.Black)};Text("Como deseja concluir?",fontWeight=FontWeight.Bold);Button({vm.checkout("reserva")},Modifier.fillMaxWidth(),enabled=!s.saving,colors=ButtonDefaults.buttonColors(containerColor=StorePlum)){Icon(Icons.Outlined.Inventory2,null);Spacer(Modifier.width(6.dp));Text("Somente reservar")};Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){Button({vm.checkout("pix")},Modifier.weight(1f),enabled=!s.saving,colors=ButtonDefaults.buttonColors(containerColor=Color(0xFF286B5A))){Text("Pagar via Pix")};Button({vm.checkout("mensalidade")},Modifier.weight(1f),enabled=!s.saving,colors=ButtonDefaults.buttonColors(containerColor=StorePeach,contentColor=StorePlum)){Text("Na mensalidade")}}}}
@Composable private fun Field(v:String,c:(String)->Unit,l:String,m:Modifier=Modifier.fillMaxWidth())=OutlinedTextField(v,c,m,label={Text(l)},singleLine=true,shape=RoundedCornerShape(15.dp));@Composable private fun EmptyStore(filho:Boolean)=Column(Modifier.fillMaxWidth().padding(35.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Outlined.Storefront,null,Modifier.size(42.dp),tint=StorePlum);Text(if(filho)"A vitrine está sendo preparada" else "Sua loja começa aqui",fontWeight=FontWeight.Black);Text(if(filho)"Os produtos publicados pela casa aparecerão aqui." else "Cadastre o primeiro item da casa.",color=AxeCloudThemeTokens.Muted,fontSize=11.sp)}
