package br.com.axecloud.app.feature.store
import br.com.axecloud.app.BuildConfig
import br.com.axecloud.app.core.network.AxeCloudHttpClient
import br.com.axecloud.app.core.session.SessionStore
import kotlinx.serialization.json.*
import java.net.URLEncoder
import javax.inject.Inject
data class StorePayload(val filho:Boolean,val products:List<StoreProduct>,val orders:List<StoreOrder>)
class StoreRepository @Inject constructor(private val http:AxeCloudHttpClient,private val sessions:SessionStore){suspend fun load():StorePayload{val s=session();val root=http.get(api("/api/v1/store/products?tenantId=${enc(s.tenantId)}"),s.accessToken).jsonObject;val products=root["data"]?.jsonArray.orEmpty().map{it.jsonObject.product()};val orders=if(s.isFilho)emptyList()else runCatching{http.get(api("/api/loja-pedidos?tenantId=${enc(s.tenantId)}&userRole=zelador"),s.accessToken).jsonObject["data"]?.jsonArray.orEmpty().map{it.jsonObject.order()}}.getOrDefault(emptyList());return StorePayload(s.isFilho,products,orders)};suspend fun save(form:ProductForm,id:String?){val s=session();check(!s.isFilho);val image=form.image.trim().ifBlank{if(id==null)runCatching{http.get(api("/api/v1/store/product-image-suggestion?q=${enc(form.name.trim())}"),s.accessToken).jsonObject.t("url")}.getOrDefault("") else ""};val body=buildJsonObject{put("tenantId",s.tenantId);put("nome",form.name.trim());put("descricao",form.description.trim());put("preco",form.price.toDoubleOrNull()?:0.0);put("estoque_atual",form.stock.toIntOrNull()?:0);put("estoque_minimo",form.minimum.toIntOrNull()?:0);put("categoria",form.category);put("imagem_url",image)};if(id==null)http.post(api("/api/v1/store/products"),body,s.accessToken)else http.patch(api("/api/v1/store/products/${enc(id)}"),body,s.accessToken)};suspend fun delete(p:StoreProduct){val s=session();http.delete(api("/api/v1/store/products/${enc(p.id)}?tenantId=${enc(s.tenantId)}"),s.accessToken)};suspend fun checkout(cart:Map<String,Int>,products:List<StoreProduct>,method:String){val s=session();http.post(api("/api/v1/store/checkout"),buildJsonObject{put("tenantId",s.tenantId);put("filhoId","");put("method",method);put("items",buildJsonArray{cart.forEach{(id,q)->products.find{it.id==id}?.let{p->add(buildJsonObject{put("produto_id",id);put("id",id);put("quantidade",q);put("nome",p.name);put("preco",p.price)})}}})},s.accessToken)};private fun session()=sessions.current().also{check(it.isAuthenticated)};private fun api(p:String)=BuildConfig.API_BASE_URL.trimEnd('/')+p;private fun enc(v:String)=URLEncoder.encode(v,"UTF-8")}
private fun JsonObject.product()=StoreProduct(t("id"),t("nome"),t("descricao"),d("preco"),i("estoque_atual"),i("estoque_minimo"),t("categoria").ifBlank{"Geral"},t("imagem_url"));private fun JsonObject.order()=StoreOrder(t("id"),t("filho_nome"),t("tipo"),t("metodo_pagamento"),t("resumo_itens"),d("valor_total"),t("created_at"));private fun JsonObject.t(k:String)=runCatching{this[k]?.jsonPrimitive?.content}.getOrNull().orEmpty();private fun JsonObject.d(k:String)=runCatching{this[k]?.jsonPrimitive?.double}.getOrNull()?:0.0;private fun JsonObject.i(k:String)=runCatching{this[k]?.jsonPrimitive?.int}.getOrNull()?:0
