package br.com.axecloud.app.feature.childprofile
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.*
import androidx.compose.ui.graphics.*
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.*
import androidx.hilt.navigation.compose.hiltViewModel
import br.com.axecloud.app.designsystem.theme.AxeCloudThemeTokens
import coil.compose.AsyncImage
private val ProfileGreen=Color(0xFF183A2B);private val ProfileGold=Color(0xFFF2C94C);private val ProfileBlue=Color(0xFF69B7CC)
@Composable fun ChildProfileRoute(vm:ChildProfileViewModel= hiltViewModel()){val s by vm.state.collectAsState();val snack=remember{SnackbarHostState()};LaunchedEffect(s.message){s.message?.let{snack.showSnackbar(it);vm.consume()}};ChildProfileScreen(s,snack,vm)}
@Composable private fun ChildProfileScreen(s:ChildProfileUiState,snack:SnackbarHostState,vm:ChildProfileViewModel){Scaffold(containerColor=AxeCloudThemeTokens.Canvas,snackbarHost={SnackbarHost(snack)}){p->if(s.loading)Box(Modifier.fillMaxSize().padding(p),contentAlignment=Alignment.Center){CircularProgressIndicator()}else Column(Modifier.fillMaxSize().padding(p).verticalScroll(rememberScrollState()).padding(17.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){ProfileHero(s.profile,{vm.edit(true)});SpiritualCrown(s.profile);CivilIdentity(s.profile);Journey(s.profile);if(s.profile.quizilas.isNotBlank())ProfileSection("Resguardos e quizilas",Icons.Outlined.Shield){Text(s.profile.quizilas,color=AxeCloudThemeTokens.Ink,lineHeight=20.sp)};s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Spacer(Modifier.height(35.dp))}};if(s.editing)ContactEditor(s.profile,s.saving,s.error,{vm.edit(false)},vm::save)}
@Composable private fun ProfileHero(p:ChildProfile,edit:()->Unit)=Surface(shape=RoundedCornerShape(30.dp),color=ProfileGreen,shadowElevation=9.dp){Box(Modifier.background(Brush.linearGradient(listOf(ProfileGreen,Color(0xFF285440))))){Column(Modifier.padding(21.dp)){Row(verticalAlignment=Alignment.CenterVertically){Surface(shape=CircleShape,border=BorderStroke(3.dp,ProfileGold),color=Color.White){if(p.photo.isNotBlank())AsyncImage(p.photo,p.name,Modifier.size(82.dp),contentScale=ContentScale.Crop)else Box(Modifier.size(82.dp),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Person,null,Modifier.size(38.dp),tint=ProfileGreen)}};Column(Modifier.weight(1f).padding(start=15.dp)){Text("MINHA IDENTIDADE NA CASA",color=ProfileGold,fontSize=9.sp,fontWeight=FontWeight.Black,letterSpacing=1.sp);Text(p.name,color=Color.White,fontSize=24.sp,fontWeight=FontWeight.Black);Text(p.role.ifBlank{"Filho de santo"},color=Color.White.copy(.65f),fontSize=11.sp);Surface(Modifier.padding(top=7.dp),shape=RoundedCornerShape(30),color=Color(0xFF67C89A).copy(.17f)){Text(p.status.ifBlank{"Ativo"}.uppercase(),Modifier.padding(horizontal=9.dp,vertical=5.dp),color=Color(0xFF80D9AE),fontSize=8.sp,fontWeight=FontWeight.Black)}};IconButton(edit){Icon(Icons.Outlined.Edit,"Editar contato",tint=Color.White)}}}}}
@Composable private fun SpiritualCrown(p:ChildProfile)=ProfileSection("Coroa e sacerdócio",Icons.Outlined.AutoAwesome){Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){ProfileValue("Orixá de frente",p.orixa.ifBlank{"Aguardando orientação"},ProfileGold,Modifier.weight(1f));ProfileValue("Adjunto",p.adjunto.ifBlank{"Não registrado"},ProfileBlue,Modifier.weight(1f))};if(p.feitura.isNotBlank())ProfileValue("Feitura / iniciação",date(p.feitura),Color(0xFF9D7ED2),Modifier.fillMaxWidth())}
@Composable private fun CivilIdentity(p:ChildProfile)=ProfileSection("Cadastro civil",Icons.Outlined.Badge){Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){ProfileValue("Nascimento",date(p.birth),ProfileBlue,Modifier.weight(1f));ProfileValue("CPF",maskCpf(p.cpf),Color(0xFF9D7ED2),Modifier.weight(1f))};ProfileValue("Contato",p.phone.ifBlank{"Não informado"},Color(0xFF5C9F75),Modifier.fillMaxWidth());ProfileValue("Endereço",p.address.ifBlank{"Não informado"},Color(0xFFC77C55),Modifier.fillMaxWidth())}
@Composable private fun Journey(p:ChildProfile)=ProfileSection("Minha caminhada",Icons.Outlined.Timeline){ProfileValue("Entrada na casa",date(p.entry),ProfileGold,Modifier.fillMaxWidth());Text(if(p.obligations.isBlank())"Os próximos marcos e obrigações aparecerão na sua jornada." else p.obligations,color=AxeCloudThemeTokens.Muted,fontSize=11.sp,lineHeight=17.sp)}
@Composable private fun ProfileSection(title:String,icon:androidx.compose.ui.graphics.vector.ImageVector,content:@Composable ColumnScope.()->Unit)=Surface(shape=RoundedCornerShape(22.dp),color=Color.White,border=BorderStroke(1.dp,AxeCloudThemeTokens.Outline)){Column(Modifier.fillMaxWidth().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(36.dp).background(ProfileGreen.copy(.08f),RoundedCornerShape(11.dp)),contentAlignment=Alignment.Center){Icon(icon,null,tint=ProfileGreen)};Text(title,Modifier.padding(start=9.dp),color=AxeCloudThemeTokens.Ink,fontSize=17.sp,fontWeight=FontWeight.Black)};content()}}
@Composable private fun ProfileValue(label:String,value:String,color:Color,modifier:Modifier)=Surface(modifier,shape=RoundedCornerShape(15.dp),color=color.copy(.09f)){Column(Modifier.padding(12.dp)){Text(label.uppercase(),color=color,fontSize=8.sp,fontWeight=FontWeight.Black);Text(value,color=AxeCloudThemeTokens.Ink,fontSize=12.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(top=3.dp))}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun ContactEditor(p:ChildProfile,saving:Boolean,error:String?,dismiss:()->Unit,save:(ChildProfile)->Unit){var phone by rememberSaveable{mutableStateOf(p.phone)};var address by rememberSaveable{mutableStateOf(p.address)};ModalBottomSheet(onDismissRequest=dismiss,containerColor=AxeCloudThemeTokens.Canvas){Column(Modifier.navigationBarsPadding().padding(horizontal=20.dp).padding(bottom=26.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){Text("Meu contato",color=AxeCloudThemeTokens.Ink,fontSize=25.sp,fontWeight=FontWeight.Black);Text("Dados espirituais são preservados pela liderança. Você pode manter seu contato atualizado.",color=AxeCloudThemeTokens.Muted,fontSize=11.sp);OutlinedTextField(phone,{phone=it},Modifier.fillMaxWidth(),label={Text("Telefone / WhatsApp")},shape=RoundedCornerShape(15.dp));OutlinedTextField(address,{address=it},Modifier.fillMaxWidth(),label={Text("Endereço")},minLines=2,shape=RoundedCornerShape(15.dp));error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button({save(p.copy(phone=phone,address=address))},Modifier.fillMaxWidth().height(52.dp),enabled=!saving,colors=ButtonDefaults.buttonColors(containerColor=ProfileGreen)){Text("Salvar meu contato")}}}}
private fun date(v:String)=if(v.isBlank())"Não informado" else runCatching{val p=v.take(10).split('-');if(p.size==3)"${p[2]}/${p[1]}/${p[0]}" else v}.getOrDefault(v);private fun maskCpf(v:String):String{val d=v.filter(Char::isDigit);return if(d.length==11)"***.${d.substring(3,6)}.${d.substring(6,9)}-**" else "Não informado"}
