package br.com.axecloud.app.feature.foundations
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.*
import androidx.compose.ui.graphics.*
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.*
import androidx.hilt.navigation.compose.hiltViewModel
import br.com.axecloud.app.designsystem.theme.AxeCloudThemeTokens
private val Herb=Color(0xFF315A43);private val Clay=Color(0xFFC98258);private val Leaf=Color(0xFF8DBA7A)
@Composable fun FoundationRoute(vm:FoundationViewModel= hiltViewModel()){val s by vm.state.collectAsState();val snack=remember{SnackbarHostState()};LaunchedEffect(s.message){s.message?.let{snack.showSnackbar(it);vm.consume()}};FoundationScreen(s,snack,vm)}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun FoundationScreen(s:FoundationUiState,snack:SnackbarHostState,vm:FoundationViewModel){Scaffold(containerColor=AxeCloudThemeTokens.Canvas,snackbarHost={SnackbarHost(snack)},floatingActionButton={if(s.manager)FloatingActionButton({vm.editor()},containerColor=Leaf,contentColor=Color(0xFF173424)){Icon(Icons.Outlined.Add,"Novo fundamento")}}){p->LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(17.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){item{FoundationHero(s)};item{OutlinedTextField(s.query,vm::query,Modifier.fillMaxWidth(),leadingIcon={Icon(Icons.Outlined.Search,null)},placeholder={Text("Buscar banho, erva ou ritual")},singleLine=true,shape=RoundedCornerShape(18.dp))};item{Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf("todos" to "Tudo","banhos" to "Banhos","ervas" to "Ervas","rituais" to "Rituais","defumacoes" to "Defumações","firmezas" to "Firmezas").forEach{(k,v)->FilterChip(s.category==k,{vm.category(k)},label={Text(v)})}}};when{s.loading->item{Box(Modifier.fillMaxWidth().padding(48.dp),contentAlignment=Alignment.Center){CircularProgressIndicator(color=Herb)}};s.error!=null&&s.items.isEmpty()->item{Text(s.error,color=MaterialTheme.colorScheme.error)};s.visible.isEmpty()->item{EmptyFoundation(s.manager)};else->itemsIndexed(s.visible,key={_,x->x.id}){i,x->AnimatedVisibility(true,enter=fadeIn()+slideInVertically{20+i*2}){FoundationCard(x,s.actionId==x.id,s.manager,{vm.select(x)},{vm.editor(x)})}}};item{Spacer(Modifier.height(70.dp))}}};if(s.editorOpen)FoundationEditor(s,{vm.editor(open=false)},vm::save);s.selected?.let{FoundationReader(it,{vm.select(null)})}}
@Composable private fun FoundationHero(s:FoundationUiState)=Surface(shape=RoundedCornerShape(30.dp),color=Herb,shadowElevation=8.dp){Box(Modifier.background(Brush.linearGradient(listOf(Herb,Color(0xFF1B382A))))){Column(Modifier.padding(22.dp)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(47.dp).background(Leaf,RoundedCornerShape(16.dp)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Spa,null,tint=Color(0xFF173424))};Column(Modifier.padding(start=12.dp)){Text("SABER PRESERVADO",color=Leaf,fontSize=9.sp,fontWeight=FontWeight.Black,letterSpacing=1.sp);Text(if(s.manager)"Acervo de fundamentos" else "Saberes liberados",color=Color.White,fontSize=25.sp,fontWeight=FontWeight.Black)}};Spacer(Modifier.height(16.dp));Text(if(s.manager)"${s.items.size} registros · ${s.published} publicados · tradição ${s.houseTradition}" else "Seu cargo, vínculo e tradição definem com segurança o que aparece aqui.",color=Color.White.copy(.68f),fontSize=11.sp)}}}
@Composable private fun FoundationCard(x:Foundation,busy:Boolean,manager:Boolean,open:()->Unit,edit:()->Unit){val c=categoryColor(x.category);Surface(Modifier.fillMaxWidth().clickable(onClick=open),shape=RoundedCornerShape(21.dp),color=Color.White,border=BorderStroke(1.dp,c.copy(.28f))){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(53.dp).background(c.copy(.14f),RoundedCornerShape(17.dp)),contentAlignment=Alignment.Center){Icon(categoryIcon(x.category),null,tint=c)};Column(Modifier.weight(1f).padding(horizontal=11.dp)){Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){Text(x.category.uppercase(),color=c,fontSize=8.sp,fontWeight=FontWeight.Black);if(manager)Text(x.status.uppercase(),color=if(x.status=="publicado")Herb else Clay,fontSize=8.sp,fontWeight=FontWeight.Bold)};Text(x.title,color=AxeCloudThemeTokens.Ink,fontWeight=FontWeight.Black,maxLines=1,overflow=TextOverflow.Ellipsis);Text(x.summary.ifBlank{"Toque para abrir o conteúdo protegido."},color=AxeCloudThemeTokens.Muted,fontSize=10.sp,maxLines=2,overflow=TextOverflow.Ellipsis);Text(accessLabel(x),color=Herb,fontSize=9.sp,fontWeight=FontWeight.Bold)};if(busy)CircularProgressIndicator(Modifier.size(18.dp),strokeWidth=2.dp)else if(manager)IconButton(edit){Icon(Icons.Outlined.Edit,null)}else Icon(Icons.Outlined.LockOpen,null,tint=Leaf)}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun FoundationReader(x:Foundation,dismiss:()->Unit)=ModalBottomSheet(onDismissRequest=dismiss,containerColor=AxeCloudThemeTokens.Canvas){Column(Modifier.navigationBarsPadding().verticalScroll(rememberScrollState()).padding(horizontal=22.dp).padding(bottom=30.dp),verticalArrangement=Arrangement.spacedBy(13.dp)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(49.dp).background(categoryColor(x.category).copy(.14f),RoundedCornerShape(15.dp)),contentAlignment=Alignment.Center){Icon(categoryIcon(x.category),null,tint=categoryColor(x.category))};Column(Modifier.padding(start=12.dp)){Text(x.category.uppercase(),color=categoryColor(x.category),fontSize=9.sp,fontWeight=FontWeight.Black);Text(x.title,color=AxeCloudThemeTokens.Ink,fontSize=24.sp,fontWeight=FontWeight.Black)}};Surface(shape=RoundedCornerShape(20.dp),color=Color.White){Text(x.content.ifBlank{x.summary},Modifier.padding(18.dp),color=AxeCloudThemeTokens.Ink,fontSize=15.sp,lineHeight=23.sp)};Text("Conteúdo interno da casa · não compartilhe sem orientação da liderança.",color=AxeCloudThemeTokens.Muted,fontSize=10.sp);Button(dismiss,Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=Herb)){Text("Concluir leitura")}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun FoundationEditor(s:FoundationUiState,dismiss:()->Unit,save:(FoundationForm)->Unit){var f by rememberSaveable(s.editor?.id){mutableStateOf(s.editor?.let(FoundationForm::from)?:FoundationForm(tradition=s.houseTradition))};ModalBottomSheet(onDismissRequest=dismiss,containerColor=AxeCloudThemeTokens.Canvas){Column(Modifier.navigationBarsPadding().verticalScroll(rememberScrollState()).padding(horizontal=20.dp).padding(bottom=28.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(if(s.editor==null)"Novo fundamento" else "Editar fundamento",color=AxeCloudThemeTokens.Ink,fontSize=25.sp,fontWeight=FontWeight.Black);Field(f.title,{f=f.copy(title=it)},"Título");Field(f.summary,{f=f.copy(summary=it)},"Resumo");Field(f.content,{f=f.copy(content=it)},"Conteúdo protegido",min=5);Text("CATEGORIA",fontSize=9.sp,fontWeight=FontWeight.Black);Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("banhos","ervas","rituais","defumacoes","firmezas","fundamentos","outros").forEach{x->FilterChip(f.category==x,{f=f.copy(category=x)},label={Text(x)})}};Field(f.tradition,{f=f.copy(tradition=it)},"Tradição (ou todas)");Text("QUEM PODE ACESSAR",fontSize=9.sp,fontWeight=FontWeight.Black);Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("corrente" to "Toda corrente","cargo" to "Por cargo","individual" to "Pessoas","zeladoria" to "Só zeladoria").forEach{(k,v)->FilterChip(f.access==k,{f=f.copy(access=k)},label={Text(v)})}};if(f.access=="cargo")Field(f.roles,{f=f.copy(roles=it)},"Cargos permitidos, separados por vírgula");if(f.access=="individual"){Text("Selecione quem terá acesso",fontWeight=FontWeight.Bold);s.children.forEach{c->ToggleChild(c,f.children.contains(c.id)){on->f=f.copy(children=if(on)f.children+c.id else f.children-c.id)}}};Row(horizontalArrangement=Arrangement.spacedBy(7.dp)){FilterChip(f.status=="rascunho",{f=f.copy(status="rascunho")},label={Text("Rascunho")});FilterChip(f.status=="publicado",{f=f.copy(status="publicado")},label={Text("Publicado")});FilterChip(f.status=="arquivado",{f=f.copy(status="arquivado")},label={Text("Arquivado")})};s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button({save(f)},Modifier.fillMaxWidth().height(54.dp),enabled=!s.saving&&f.title.length>=3&&f.content.length>=3,colors=ButtonDefaults.buttonColors(containerColor=Herb)){Text(if(f.status=="publicado")"Salvar e controlar acesso" else "Salvar no acervo")}}}
}
@Composable private fun ToggleChild(c:FoundationChild,on:Boolean,change:(Boolean)->Unit)=Row(Modifier.fillMaxWidth().background(Color.White,RoundedCornerShape(14.dp)).clickable{change(!on)}.padding(11.dp),verticalAlignment=Alignment.CenterVertically){Checkbox(on,change);Column{Text(c.name,fontWeight=FontWeight.Bold);Text(c.role.ifBlank{"Filho de santo"},color=AxeCloudThemeTokens.Muted,fontSize=9.sp)}}
@Composable private fun Field(v:String,c:(String)->Unit,l:String,m:Modifier=Modifier.fillMaxWidth(),min:Int=1)=OutlinedTextField(v,c,m,label={Text(l)},minLines=min,maxLines=if(min>1)12 else 1,shape=RoundedCornerShape(15.dp))
@Composable private fun EmptyFoundation(manager:Boolean)=Column(Modifier.fillMaxWidth().padding(35.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Outlined.Spa,null,Modifier.size(44.dp),tint=Herb);Text(if(manager)"O saber aguarda registro" else "Nenhum fundamento liberado",fontWeight=FontWeight.Black);Text(if(manager)"Preserve banhos, ervas e rituais com acesso responsável." else "A liderança libera os conteúdos conforme sua função.",color=AxeCloudThemeTokens.Muted,fontSize=11.sp)}
private fun categoryColor(c:String)=when(c){"ervas","banhos"->Herb;"rituais","firmezas"->Clay;else->Color(0xFF6E5B9B)}
private fun categoryIcon(c:String)=when(c){"ervas"->Icons.Outlined.Grass;"banhos"->Icons.Outlined.WaterDrop;"rituais"->Icons.Outlined.LocalFireDepartment;else->Icons.Outlined.AutoStories}
private fun accessLabel(x:Foundation)=when(x.access){"cargo"->"Liberado para: ${x.roles.joinToString()}";"individual"->"Acesso individual";"zeladoria"->"Somente zeladoria";else->"Toda a corrente"}
