package br.com.axecloud.app.feature.foundations
import br.com.axecloud.app.BuildConfig
import br.com.axecloud.app.core.network.AxeCloudHttpClient
import br.com.axecloud.app.core.session.SessionStore
import kotlinx.serialization.json.*
import java.net.URLEncoder
import javax.inject.Inject
data class FoundationPayload(val manager:Boolean,val items:List<Foundation>,val children:List<FoundationChild>,val tradition:String)
class FoundationRepository @Inject constructor(private val http:AxeCloudHttpClient,private val sessions:SessionStore){suspend fun load():FoundationPayload{val s=session();val root=http.get(api("/api/v1/fundamentos?tenantId=${enc(s.tenantId)}"),s.accessToken).jsonObject;val manager=root.t("role")=="manager";val options=if(manager)runCatching{http.get(api("/api/v1/fundamentos/options?tenantId=${enc(s.tenantId)}"),s.accessToken).jsonObject}.getOrDefault(JsonObject(emptyMap()))else JsonObject(emptyMap());return FoundationPayload(manager,root["data"]?.jsonArray.orEmpty().map{it.jsonObject.model()},options["children"]?.jsonArray.orEmpty().map{val o=it.jsonObject;FoundationChild(o.t("id"),o.t("nome"),o.t("cargo"))},options.t("tradition").ifBlank{"todas"})};suspend fun detail(id:String):Foundation{val s=session();return http.get(api("/api/v1/fundamentos/${enc(id)}?tenantId=${enc(s.tenantId)}"),s.accessToken).jsonObject["data"]!!.jsonObject.model()};suspend fun save(form:FoundationForm,id:String?){val s=session();val body=buildJsonObject{put("tenantId",s.tenantId);put("titulo",form.title);put("resumo",form.summary);put("conteudo",form.content);put("categoria",form.category);put("tradicao",form.tradition);put("nivel_acesso",form.access);put("cargos_permitidos",JsonArray(form.roles.split(',').map{it.trim()}.filter{it.isNotBlank()}.map(::JsonPrimitive)));put("filhos_permitidos",JsonArray(form.children.map(::JsonPrimitive)));put("status",form.status)};if(id==null)http.post(api("/api/v1/fundamentos"),body,s.accessToken)else http.patch(api("/api/v1/fundamentos/${enc(id)}"),body,s.accessToken)};private fun session()=sessions.current().also{check(it.isAuthenticated)};private fun api(p:String)=BuildConfig.API_BASE_URL.trimEnd('/')+p;private fun enc(v:String)=URLEncoder.encode(v,"UTF-8")}
private fun JsonObject.model()=Foundation(t("id"),t("titulo"),t("resumo"),t("conteudo"),t("categoria"),t("tradicao"),t("nivel_acesso"),list("cargos_permitidos"),list("filhos_permitidos"),t("status"),t("updated_at"));private fun JsonObject.t(k:String)=runCatching{this[k]?.jsonPrimitive?.content}.getOrNull().orEmpty();private fun JsonObject.list(k:String)=runCatching{this[k]?.jsonArray?.map{it.jsonPrimitive.content}}.getOrNull().orEmpty()
