FROM caddy:2-builder AS builder
RUN xcaddy build \
    --with github.com/mholt/caddy-ratelimit@5625512f24f6f59d6f64fb3aafe5eecff0b286db \
    --with github.com/hslatman/caddy-crowdsec-bouncer/http@8814a3118b7308319edd647844d0acf2d7d2443a \
    --with github.com/hslatman/caddy-crowdsec-bouncer/appsec@8814a3118b7308319edd647844d0acf2d7d2443a

FROM caddy:2-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
