package br.com.axecloud.app.feature.settings
import android.content.Intent
import android.provider.Settings
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.*
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.*
import androidx.hilt.navigation.compose.hiltViewModel
import br.com.axecloud.app.designsystem.theme.AxeCloudThemeTokens
private val SettingsBlue=Color(0xFF2D5E75);private val SettingsSky=Color(0xFF73CBE7)
@Composable fun SettingsRoute(vm:SettingsViewModel= hiltViewModel()){val s by vm.state.collectAsState();val snack=remember{SnackbarHostState()};LaunchedEffect(s.message){s.message?.let{snack.showSnackbar(it);vm.consume()}};SettingsScreen(s,snack,vm)}
@Composable private fun SettingsScreen(s:SettingsUiState,snack:SnackbarHostState,vm:SettingsViewModel){val ctx=LocalContext.current;Scaffold(containerColor=AxeCloudThemeTokens.Canvas,snackbarHost={SnackbarHost(snack)}){p->Column(Modifier.fillMaxSize().padding(p)){if(s.loading)Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()}else{Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(17.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){SettingsHero(s);Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf("identidade" to "Identidade","portal" to "Portal público","notificacoes" to "Notificações","plano" to "Plano").forEach{(k,v)->FilterChip(s.section==k,{vm.section(k)},label={Text(v)})}};when(s.section){"identidade"->IdentityForm(s.identity,vm::identity);"portal"->PortalForm(s.portal,vm::portal);"notificacoes"->NotificationSettings{ctx.startActivity(Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,ctx.packageName))};else->PlanSettings(s.plan)};s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)};if(s.section in listOf("identidade","portal"))Button(vm::save,Modifier.fillMaxWidth().height(54.dp),enabled=!s.saving,colors=ButtonDefaults.buttonColors(containerColor=SettingsBlue),shape=RoundedCornerShape(17.dp)){Text("Salvar alterações")};Spacer(Modifier.height(30.dp))}}}}}
@Composable private fun SettingsHero(s:SettingsUiState)=Surface(shape=RoundedCornerShape(29.dp),color=SettingsBlue,shadowElevation=8.dp){Box(Modifier.background(Brush.linearGradient(listOf(SettingsBlue,Color(0xFF183A49))))){Column(Modifier.padding(22.dp)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(46.dp).background(SettingsSky,RoundedCornerShape(16.dp)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Tune,null,tint=SettingsBlue)};Column(Modifier.padding(start=12.dp)){Text("CENTRAL DA CASA",color=SettingsSky,fontSize=9.sp,fontWeight=FontWeight.Black,letterSpacing=1.sp);Text("Configurações",color=Color.White,fontSize=27.sp,fontWeight=FontWeight.Black)}};Text("Identidade, presença pública e preferências reunidas com clareza.",color=Color.White.copy(.65f),fontSize=11.sp,modifier=Modifier.padding(top=15.dp))}}}
@Composable private fun IdentityForm(v:IdentitySettings,on:(IdentitySettings)->Unit)=SettingsPanel("Identidade da casa",Icons.Outlined.Badge){Field(v.houseName,{on(v.copy(houseName=it))},"Nome do terreiro");Field(v.leaderName,{on(v.copy(leaderName=it))},"Nome do zelador(a)");Field(v.role,{on(v.copy(role=it))},"Cargo litúrgico");Field(v.email,{},"E-mail de acesso",enabled=false)}
@Composable private fun PortalForm(v:PortalSettings,on:(PortalSettings)->Unit)=SettingsPanel("Presença pública",Icons.Outlined.Public){Toggle("Exibir no diretório público",v.publicActive){on(v.copy(publicActive=it))};Toggle("Receber pedidos de reza",v.prayerActive){on(v.copy(prayerActive=it))};Field(v.slug,{on(v.copy(slug=it))},"Endereço público");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Field(v.city,{on(v.copy(city=it))},"Cidade",Modifier.weight(1f));Field(v.state,{on(v.copy(state=it.uppercase().take(2)))},"UF",Modifier.weight(.4f))};Field(v.neighborhood,{on(v.copy(neighborhood=it))},"Bairro");Field(v.whatsapp,{on(v.copy(whatsapp=it))},"WhatsApp público");Field(v.description,{on(v.copy(description=it))},"Apresentação da casa",minLines=3);Field(v.prayerMessage,{on(v.copy(prayerMessage=it))},"Mensagem de acolhimento",minLines=2);Text("${v.views} visualizações do perfil",color=SettingsBlue,fontWeight=FontWeight.Bold,fontSize=11.sp)}
@Composable private fun NotificationSettings(open:()->Unit)=SettingsPanel("Avisos do aplicativo",Icons.Outlined.NotificationsActive){Text("O Android controla som, vibração, tela bloqueada e permissões do AxéCloud.",color=AxeCloudThemeTokens.Muted,fontSize=12.sp);Button(open,Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(containerColor=SettingsBlue)){Text("Abrir permissões do Android")};Info("Pendências reais","Mensalidades, giras, preceitos e comunicados alimentam a caixa nativa.");Info("Push em segundo plano","Será ativado com o projeto Firebase da publicação na Play Store.")}
@Composable private fun PlanSettings(plan:String)=SettingsPanel("Assinatura AxéCloud",Icons.Outlined.WorkspacePremium){Text(plan.ifBlank{"Plano atual"}.uppercase(),color=SettingsBlue,fontSize=22.sp,fontWeight=FontWeight.Black);Text("A gestão da assinatura permanece protegida no checkout oficial.",color=AxeCloudThemeTokens.Muted,fontSize=12.sp);Info("Aplicativo Android","Incluído para a liderança e para toda a corrente.");Info("Dados sincronizados","O app e o painel web usam a mesma casa no Supabase.")}
@Composable private fun SettingsPanel(title:String,icon:androidx.compose.ui.graphics.vector.ImageVector,content:@Composable ColumnScope.()->Unit)=Surface(shape=RoundedCornerShape(22.dp),color=Color.White,border=BorderStroke(1.dp,AxeCloudThemeTokens.Outline)){Column(Modifier.fillMaxWidth().padding(17.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){Row(verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=SettingsBlue);Text(title,Modifier.padding(start=9.dp),color=AxeCloudThemeTokens.Ink,fontSize=18.sp,fontWeight=FontWeight.Black)};content()}}
@Composable private fun Field(v:String,c:(String)->Unit,l:String,m:Modifier=Modifier.fillMaxWidth(),enabled:Boolean=true,minLines:Int=1)=OutlinedTextField(v,c,m,label={Text(l)},enabled=enabled,minLines=minLines,maxLines=if(minLines>1)5 else 1,shape=RoundedCornerShape(15.dp));@Composable private fun Toggle(t:String,v:Boolean,c:(Boolean)->Unit)=Row(Modifier.fillMaxWidth().background(AxeCloudThemeTokens.Canvas,RoundedCornerShape(15.dp)).padding(12.dp),verticalAlignment=Alignment.CenterVertically){Text(t,Modifier.weight(1f),fontWeight=FontWeight.Bold);Switch(v,c)};@Composable private fun Info(t:String,d:String)=Row{Icon(Icons.Outlined.CheckCircle,null,tint=SettingsSky);Column(Modifier.padding(start=8.dp)){Text(t,fontWeight=FontWeight.Bold);Text(d,color=AxeCloudThemeTokens.Muted,fontSize=10.sp)}}
