package br.com.axecloud.app.feature.settings
import br.com.axecloud.app.BuildConfig
import br.com.axecloud.app.core.network.AxeCloudHttpClient
import br.com.axecloud.app.core.session.SessionStore
import kotlinx.serialization.json.*
import javax.inject.Inject
data class SettingsPayload(val identity:IdentitySettings,val portal:PortalSettings,val plan:String)
class SettingsRepository @Inject constructor(private val http:AxeCloudHttpClient,private val sessions:SessionStore){suspend fun load():SettingsPayload{val s=session();check(!s.isFilho){"Configurações da casa são exclusivas da liderança."};val o=http.get(api("/api/v1/settings/portal-consulente"),s.accessToken).jsonObject;return SettingsPayload(IdentitySettings(o.t("nomeTerreiro").ifBlank{s.houseName},"",s.role.ifBlank{"Zelador"},s.email,s.profilePhotoUrl),PortalSettings(o.t("tradicao").ifBlank{"mista"},o.t("publicSlug"),o.b("portalAtivo"),o.t("mensagem"),o.b("portalPublicoAtivo"),o.t("cidadePublica"),o.t("estadoPublico"),o.t("bairroPublico"),o.t("whatsappPublico"),o.t("descricaoPublica"),o.i("visualizacoes"),o.t("terreiroUrl","portalUrl")),s.plan)};suspend fun saveIdentity(v:IdentitySettings){val s=session();http.post(api("/api/v1/settings/save"),buildJsonObject{put("userId",s.userId);put("tenantId",s.tenantId);put("profile",buildJsonObject{put("email",s.email);put("nome_terreiro",v.houseName);put("cargo",v.role);put("zelador",v.leaderName.ifBlank{v.role});put("foto_url",v.photo)})},s.accessToken)};suspend fun savePortal(v:PortalSettings){val s=session();http.post(api("/api/v1/settings/portal-consulente"),buildJsonObject{put("tradicao",v.tradition);put("publicSlug",v.slug);put("portalAtivo",v.prayerActive);put("mensagem",v.prayerMessage);put("portalPublicoAtivo",v.publicActive);put("cidadePublica",v.city);put("estadoPublico",v.state);put("bairroPublico",v.neighborhood);put("whatsappPublico",v.whatsapp);put("descricaoPublica",v.description)},s.accessToken)};private fun session()=sessions.current().also{check(it.isAuthenticated)};private fun api(p:String)=BuildConfig.API_BASE_URL.trimEnd('/')+p}
private fun JsonObject.t(vararg k:String)=k.firstNotNullOfOrNull{x->runCatching{this[x]?.jsonPrimitive?.content}.getOrNull()?.takeIf(String::isNotBlank)}.orEmpty();private fun JsonObject.b(k:String):Boolean=runCatching{this[k]?.jsonPrimitive?.boolean}.getOrNull()?:false;private fun JsonObject.i(k:String):Int=runCatching{this[k]?.jsonPrimitive?.int}.getOrNull()?:0
