package br.com.axecloud.app.feature.care
import android.content.Intent
import android.net.Uri
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.graphics.*
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.*
import androidx.hilt.navigation.compose.hiltViewModel
import br.com.axecloud.app.designsystem.theme.AxeCloudThemeTokens
private val CareInk=Color(0xFF271C2B);private val CareRose=Color(0xFFE6819A);private val CareLilac=Color(0xFFBDA7E8)
@Composable fun CareRoute(vm:CareViewModel= hiltViewModel()){val s by vm.state.collectAsState();val snack=remember{SnackbarHostState()};LaunchedEffect(s.message){s.message?.let{snack.showSnackbar(it);vm.consume()}};CareScreen(s,snack,vm)}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun CareScreen(s:CareUiState,snack:SnackbarHostState,vm:CareViewModel){Scaffold(containerColor=AxeCloudThemeTokens.Canvas,snackbarHost={SnackbarHost(snack)}){p->LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(17.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){item{CareHero(s)};item{OutlinedTextField(s.query,vm::query,Modifier.fillMaxWidth(),leadingIcon={Icon(Icons.Outlined.Search,null)},placeholder={Text("Buscar pessoa ou intenção")},singleLine=true,shape=RoundedCornerShape(18.dp))};item{Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf("todos" to "Todos","pendente" to "Aguardando","aceito" to "Acolhidos","em_oracao" to "Em oração").forEach{(k,v)->FilterChip(s.filter==k,{vm.filter(k)},label={Text(v)})}}};when{s.loading->item{Box(Modifier.fillMaxWidth().padding(48.dp),contentAlignment=Alignment.Center){CircularProgressIndicator(color=CareRose)}};s.error!=null&&s.requests.isEmpty()->item{Text(s.error,color=MaterialTheme.colorScheme.error)};s.visible.isEmpty()->item{EmptyCare()};else->itemsIndexed(s.visible,key={_,r->r.id}){i,r->AnimatedVisibility(true,enter=fadeIn()+slideInVertically{20+i*2}){CareCard(r,s.actionId==r.id,{vm.select(r)},{vm.update(r,"aceito")})}}};item{Spacer(Modifier.height(40.dp))}}};s.selected?.let{CareDetail(it,s.actionId==it.id,{vm.select(null)},vm::update)}}
@Composable private fun CareHero(s:CareUiState)=Surface(shape=RoundedCornerShape(30.dp),color=CareInk,shadowElevation=8.dp){Box(Modifier.background(Brush.linearGradient(listOf(CareInk,Color(0xFF4B2741))))){Column(Modifier.padding(22.dp)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(46.dp).background(CareRose,RoundedCornerShape(16.dp)),contentAlignment=Alignment.Center){Icon(Icons.Outlined.VolunteerActivism,null,tint=Color.White)};Column(Modifier.padding(start=12.dp)){Text("ESCUTA E ACOLHIMENTO",color=CareRose,fontSize=9.sp,fontWeight=FontWeight.Black,letterSpacing=1.sp);Text("Atendimentos",color=Color.White,fontSize=27.sp,fontWeight=FontWeight.Black)}};Spacer(Modifier.height(18.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){CareMetric(s.pending,"aguardando",CareRose,Modifier.weight(1f));CareMetric(s.accepted,"acolhidos",CareLilac,Modifier.weight(1f));CareMetric(s.inPrayer,"em oração",Color(0xFFFFD166),Modifier.weight(1f))}}}}
@Composable private fun CareMetric(v:Int,l:String,c:Color,m:Modifier)=Surface(m,shape=RoundedCornerShape(14.dp),color=Color.White.copy(.07f)){Column(Modifier.padding(11.dp)){Text(v.toString(),color=c,fontSize=22.sp,fontWeight=FontWeight.Black);Text(l,color=Color.White.copy(.6f),fontSize=8.sp)}}
@Composable private fun CareCard(r:PrayerRequest,busy:Boolean,open:()->Unit,accept:()->Unit){val c=statusColor(r.status);Surface(Modifier.fillMaxWidth().clickable(onClick=open),shape=RoundedCornerShape(21.dp),color=Color.White,border=BorderStroke(1.dp,c.copy(.25f))){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(47.dp).background(c.copy(.14f),CircleShape),contentAlignment=Alignment.Center){Icon(Icons.Outlined.Spa,null,tint=c)};Column(Modifier.weight(1f).padding(horizontal=11.dp)){Text(r.name,color=AxeCloudThemeTokens.Ink,fontWeight=FontWeight.Black,maxLines=1,overflow=TextOverflow.Ellipsis);Text(r.message,color=AxeCloudThemeTokens.Muted,fontSize=10.sp,maxLines=2,overflow=TextOverflow.Ellipsis);Text("${statusLabel(r.status)} · ${r.candle.ifBlank{"sem vela"}}",color=c,fontSize=9.sp,fontWeight=FontWeight.Bold)};if(r.status=="pendente")Button(accept,enabled=!busy,contentPadding=PaddingValues(horizontal=12.dp),colors=ButtonDefaults.buttonColors(containerColor=CareInk)){Text("Acolher",fontSize=10.sp)}else Icon(Icons.Outlined.ChevronRight,null,tint=AxeCloudThemeTokens.Muted)}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun CareDetail(r:PrayerRequest,busy:Boolean,dismiss:()->Unit,update:(PrayerRequest,String,String?)->Unit){var note by remember(r.id){mutableStateOf(r.note)};val ctx=LocalContext.current;ModalBottomSheet(onDismissRequest=dismiss,containerColor=AxeCloudThemeTokens.Canvas){Column(Modifier.navigationBarsPadding().verticalScroll(rememberScrollState()).padding(horizontal=20.dp).padding(bottom=26.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(50.dp).background(CareRose.copy(.16f),CircleShape),contentAlignment=Alignment.Center){Icon(Icons.Outlined.VolunteerActivism,null,tint=CareRose)};Column(Modifier.weight(1f).padding(start=12.dp)){Text(r.name,color=AxeCloudThemeTokens.Ink,fontSize=23.sp,fontWeight=FontWeight.Black);Text(statusLabel(r.status),color=statusColor(r.status),fontSize=10.sp,fontWeight=FontWeight.Bold)}};Surface(shape=RoundedCornerShape(18.dp),color=Color.White){Column(Modifier.padding(16.dp)){Text("INTENÇÃO",color=CareRose,fontSize=9.sp,fontWeight=FontWeight.Black);Text(r.message,color=AxeCloudThemeTokens.Ink,fontSize=15.sp,modifier=Modifier.padding(top=5.dp));HorizontalDivider(Modifier.padding(vertical=12.dp));Text("${r.category.ifBlank{"Pedido de reza"}} · ${r.line.ifBlank{"Linha não informada"}} · Vela ${r.candle.ifBlank{"não solicitada"}}",color=AxeCloudThemeTokens.Muted,fontSize=10.sp)}};if(r.whatsapp.isNotBlank())OutlinedButton({ctx.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("https://wa.me/${r.whatsapp.filter(Char::isDigit)}")))},Modifier.fillMaxWidth()){Icon(Icons.Outlined.Chat,null);Spacer(Modifier.width(7.dp));Text("Falar com ${r.name}")};OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),label={Text("Anotação interna")},minLines=2,shape=RoundedCornerShape(16.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){when(r.status){"pendente"->Button({update(r,"aceito",note)},Modifier.weight(1f),enabled=!busy,colors=ButtonDefaults.buttonColors(containerColor=CareInk)){Text("Acolher pedido")};"aceito"->Button({update(r,"em_oracao",note)},Modifier.weight(1f),enabled=!busy,colors=ButtonDefaults.buttonColors(containerColor=CareInk)){Text("Iniciar reza")};else->Button({update(r,"aceito",note)},Modifier.weight(1f),enabled=!busy,colors=ButtonDefaults.buttonColors(containerColor=CareInk)){Text("Pausar")}};Button({update(r,"concluido",note)},Modifier.weight(1f),enabled=!busy,colors=ButtonDefaults.buttonColors(containerColor=Color(0xFF426C5A))){Text("Concluir")}}}}}
@Composable private fun EmptyCare()=Surface(shape=RoundedCornerShape(23.dp),color=Color.White,border=BorderStroke(1.dp,AxeCloudThemeTokens.Outline)){Column(Modifier.fillMaxWidth().padding(30.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Outlined.Spa,null,Modifier.size(42.dp),tint=CareRose);Text("A casa está em paz",color=AxeCloudThemeTokens.Ink,fontSize=19.sp,fontWeight=FontWeight.Black);Text("Novos pedidos enviados pelo portal aparecerão aqui.",color=AxeCloudThemeTokens.Muted,fontSize=11.sp)}}
private fun statusColor(s:String)=when(s){"pendente"->CareRose;"em_oracao"->Color(0xFFD49721);else->Color(0xFF6C5AA7)};private fun statusLabel(s:String)=when(s){"pendente"->"Aguardando acolhimento";"aceito"->"Acolhido";"em_oracao"->"Em oração";else->"Concluído"}
