-- Funil pós-aprovação das reivindicações do diretório.
-- Mantém eventos operacionais separados das métricas anônimas de aquisição,
-- pois os lembretes e o console precisam acompanhar uma reivindicação concreta.
create table if not exists public.terreiro_claim_activation_events (
  id bigint generated by default as identity primary key,
  claim_id uuid not null references public.terreiro_claim_requests(id) on delete cascade,
  event_type text not null,
  delivery_id uuid null references public.whatsapp_deliveries(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint terreiro_claim_activation_event_type_check check (event_type in (
    'approved',
    'notification_sent',
    'activation_opened',
    'activation_started',
    'activation_completed',
    'reminder_24h_sent',
    'reminder_72h_sent'
  )),
  constraint terreiro_claim_activation_event_once unique (claim_id, event_type)
);

create index if not exists terreiro_claim_activation_events_claim_created_idx
  on public.terreiro_claim_activation_events (claim_id, created_at asc);

create index if not exists terreiro_claim_activation_events_type_created_idx
  on public.terreiro_claim_activation_events (event_type, created_at desc);

alter table public.terreiro_claim_activation_events enable row level security;
revoke all on table public.terreiro_claim_activation_events from anon, authenticated;

comment on table public.terreiro_claim_activation_events is
  'Etapas operacionais do convite de reivindicação aprovada até a conexão da casa.';

-- Novas etapas anônimas para leitura agregada do funil público.
alter table public.public_conversion_events
  drop constraint if exists public_conversion_events_event_name_check;

alter table public.public_conversion_events
  add constraint public_conversion_events_event_name_check
  check (event_name in (
    'landing_view',
    'commercial_view',
    'section_view',
    'cta_click',
    'commercial_cta_click',
    'trial_cta_click',
    'login_click',
    'directory_view',
    'directory_action',
    'claim_started',
    'claim_completed',
    'claim_activation_opened',
    'claim_activation_started',
    'claim_activation_completed',
    'register_view',
    'register_started',
    'register_step_completed',
    'register_submitted',
    'register_failed',
    'register_completed',
    'directory_performance'
  ));
