-- Central global de auditoria dos envios WhatsApp.
-- Independente de tenant: reivindicacoes e mensagens operacionais precisam ser
-- rastreadas mesmo antes de existir uma conta AxeCloud vinculada.

create table if not exists public.whatsapp_deliveries (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid null,
  recipient_phone text not null,
  recipient_name text null,
  channel text not null default 'meta_cloud',
  message_kind text not null,
  template_name text null,
  template_language text null,
  source text not null default 'system',
  source_id text null,
  status text not null default 'queued',
  external_id text null,
  idempotency_key text null,
  retry_of_id uuid null references public.whatsapp_deliveries(id) on delete set null,
  requested_by uuid null,
  attempt_number integer not null default 1,
  request_payload jsonb not null default '{}'::jsonb,
  response_payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  error_code text null,
  error_message text null,
  queued_at timestamptz not null default now(),
  sending_at timestamptz null,
  accepted_at timestamptz null,
  sent_at timestamptz null,
  delivered_at timestamptz null,
  read_at timestamptz null,
  failed_at timestamptz null,
  last_webhook_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whatsapp_deliveries_channel_check
    check (channel in ('meta_cloud', 'evolution', 'baileys')),
  constraint whatsapp_deliveries_kind_check
    check (message_kind in ('template', 'text')),
  constraint whatsapp_deliveries_status_check
    check (status in ('queued', 'sending', 'accepted', 'sent', 'delivered', 'read', 'failed', 'unknown'))
);

create unique index if not exists whatsapp_deliveries_external_id_uidx
  on public.whatsapp_deliveries (external_id)
  where external_id is not null;

create unique index if not exists whatsapp_deliveries_idempotency_uidx
  on public.whatsapp_deliveries (idempotency_key)
  where idempotency_key is not null;

create index if not exists whatsapp_deliveries_created_idx
  on public.whatsapp_deliveries (created_at desc);

create index if not exists whatsapp_deliveries_status_created_idx
  on public.whatsapp_deliveries (status, created_at desc);

create index if not exists whatsapp_deliveries_source_idx
  on public.whatsapp_deliveries (source, source_id, created_at desc);

create index if not exists whatsapp_deliveries_phone_idx
  on public.whatsapp_deliveries (recipient_phone, created_at desc);

create table if not exists public.whatsapp_delivery_events (
  id bigint generated by default as identity primary key,
  delivery_id uuid not null references public.whatsapp_deliveries(id) on delete cascade,
  status text not null,
  event_type text not null,
  event_key text null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint whatsapp_delivery_events_status_check
    check (status in ('queued', 'sending', 'accepted', 'sent', 'delivered', 'read', 'failed', 'unknown'))
);

create unique index if not exists whatsapp_delivery_events_key_uidx
  on public.whatsapp_delivery_events (delivery_id, event_key)
  where event_key is not null;

create index if not exists whatsapp_delivery_events_delivery_idx
  on public.whatsapp_delivery_events (delivery_id, created_at asc);

alter table public.whatsapp_deliveries enable row level security;
alter table public.whatsapp_delivery_events enable row level security;

-- Sem policies para anon/authenticated. O console usa service_role e valida
-- administrador global na API antes de expor qualquer dado.
revoke all on table public.whatsapp_deliveries from anon, authenticated;
revoke all on table public.whatsapp_delivery_events from anon, authenticated;

comment on table public.whatsapp_deliveries is
  'Fonte global da verdade para tentativa, aceite Meta, entrega, leitura e falha de mensagens WhatsApp.';
comment on table public.whatsapp_delivery_events is
  'Linha do tempo imutavel de cada mensagem WhatsApp rastreada.';

notify pgrst, 'reload schema';
