package br.com.axecloud.app.feature.inventory
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.*
import androidx.hilt.navigation.compose.hiltViewModel
import br.com.axecloud.app.designsystem.theme.AxeCloudThemeTokens

@Composable fun InventoryRoute(vm:InventoryViewModel= hiltViewModel()){val s by vm.state.collectAsState();val snack=remember{SnackbarHostState()};LaunchedEffect(s.message){s.message?.let{snack.showSnackbar(it);vm.consume()}};InventoryScreen(s,snack,vm)}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun InventoryScreen(s:InventoryUiState,snack:SnackbarHostState,vm:InventoryViewModel){var remove by remember{mutableStateOf<InventoryItem?>(null)};Scaffold(containerColor=AxeCloudThemeTokens.Canvas,snackbarHost={SnackbarHost(snack)},floatingActionButton={FloatingActionButton(vm::create,containerColor=AxeCloudThemeTokens.Gold,contentColor=AxeCloudThemeTokens.ForestDeep,shape=RoundedCornerShape(18.dp)){Icon(Icons.Outlined.Add,"Novo item")}}){p->LazyColumn(Modifier.fillMaxSize().padding(p),contentPadding=PaddingValues(horizontal=18.dp,vertical=16.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){item{InventoryHero(s)};item{OutlinedTextField(s.query,vm::query,Modifier.fillMaxWidth(),singleLine=true,leadingIcon={Icon(Icons.Outlined.Search,null)},placeholder={Text("Buscar item ou categoria")},shape=RoundedCornerShape(18.dp))};item{Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("todos" to "Todos ${s.items.size}","baixo" to "Baixo ${s.items.count{it.quantity in 1..it.minimum}}","esgotado" to "Esgotado ${s.items.count{it.quantity==0}}","em_dia" to "Em dia ${s.items.count{it.quantity>it.minimum}}").forEach{(k,l)->FilterChip(s.status==k,{vm.status(k)},label={Text(l)})}}};item{Row(Modifier.horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){s.categories.forEach{c->AssistChip({vm.category(c)},label={Text(c)},colors=AssistChipDefaults.assistChipColors(containerColor=if(s.category==c)Color(0xFF68D1D9).copy(.18f)else Color.Transparent))}}};when{ s.loading->item{Box(Modifier.fillMaxWidth().padding(50.dp),contentAlignment=Alignment.Center){CircularProgressIndicator(color=AxeCloudThemeTokens.Forest)}};s.error!=null&&s.items.isEmpty()->item{Text(s.error,color=MaterialTheme.colorScheme.error)};s.visible.isEmpty()->item{EmptyStock(s.status=="baixo"||s.status=="esgotado")};else->items(s.visible,key={it.id}){i->StockRow(i,s.actionId?.startsWith(i.id)==true,{vm.edit(i)},{remove=i},{vm.adjust(i,-1)},{vm.adjust(i,1)})}};item{Spacer(Modifier.height(80.dp))}}};if(s.creating||s.editing!=null)InventoryEditor(s.editing,s.saving,s.error,vm::close,vm::save);remove?.let{i->AlertDialog(onDismissRequest={remove=null},title={Text("Excluir ${i.name}?")},text={Text("O item será removido do almoxarifado.")},confirmButton={Button({remove=null;vm.delete(i)},colors=ButtonDefaults.buttonColors(containerColor=MaterialTheme.colorScheme.error)){Text("Excluir")}},dismissButton={TextButton({remove=null}){Text("Cancelar")}})}}
@Composable private fun InventoryHero(s:InventoryUiState)=Surface(shape=RoundedCornerShape(27.dp),color=Color(0xFF183744)){Column(Modifier.fillMaxWidth().padding(22.dp)){Row(verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(14.dp),color=Color(0xFF68D1D9)){Icon(Icons.Outlined.Inventory2,null,Modifier.padding(11.dp),tint=Color(0xFF102D35))};Column(Modifier.padding(start=12.dp)){Text("GUARDA E PREPARO",color=Color(0xFF68D1D9),fontSize=10.sp,fontWeight=FontWeight.Black,letterSpacing=1.sp);Text("Almoxarifado",color=Color.White,fontSize=27.sp,fontWeight=FontWeight.Black)}};Spacer(Modifier.height(18.dp));Row(horizontalArrangement=Arrangement.spacedBy(9.dp)){Metric(s.items.size.toString(),"itens",Modifier.weight(1f));Metric(s.lowCount.toString(),"pedem reposição",Modifier.weight(1f))}}}
@Composable private fun Metric(v:String,l:String,m:Modifier)=Surface(m,shape=RoundedCornerShape(15.dp),color=Color.White.copy(.08f)){Column(Modifier.padding(13.dp)){Text(v,color=Color(0xFF68D1D9),fontSize=23.sp,fontWeight=FontWeight.Black);Text(l,color=Color.White.copy(.65f),fontSize=10.sp)}}
@Composable private fun StockRow(i:InventoryItem,busy:Boolean,edit:()->Unit,delete:()->Unit,minus:()->Unit,plus:()->Unit){val low=i.quantity<=i.minimum;val color=if(low)Color(0xFFC06835)else Color(0xFF287C69);Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(19.dp),color=Color.White,border=BorderStroke(1.dp,if(low)color.copy(.3f)else AxeCloudThemeTokens.Outline)){Column{Row(Modifier.clickable(onClick=edit).padding(horizontal=14.dp,vertical=12.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(44.dp).background(color.copy(.1f),RoundedCornerShape(14.dp)),contentAlignment=Alignment.Center){Icon(if(low)Icons.Outlined.WarningAmber else Icons.Outlined.Inventory2,null,tint=color)};Column(Modifier.weight(1f).padding(horizontal=11.dp)){Text(i.name,color=AxeCloudThemeTokens.Ink,fontWeight=FontWeight.ExtraBold,maxLines=1,overflow=TextOverflow.Ellipsis);Text(i.category,color=AxeCloudThemeTokens.Muted,fontSize=10.sp);Text(if(low)"Repor até ${i.minimum}" else "Estoque saudável",color=color,fontSize=9.sp,fontWeight=FontWeight.Bold)};Text(i.quantity.toString(),color=color,fontSize=24.sp,fontWeight=FontWeight.Black);IconButton(delete){Icon(Icons.Outlined.DeleteOutline,"Excluir",tint=AxeCloudThemeTokens.Muted)}};HorizontalDivider(color=AxeCloudThemeTokens.Outline);Row(Modifier.fillMaxWidth().padding(horizontal=10.dp,vertical=4.dp),verticalAlignment=Alignment.CenterVertically){Text("AJUSTE RÁPIDO",Modifier.weight(1f),color=AxeCloudThemeTokens.Muted,fontSize=8.sp,fontWeight=FontWeight.Black);IconButton(minus,enabled=!busy&&i.quantity>0){Icon(Icons.Outlined.RemoveCircleOutline,"Retirar uma unidade",tint=color)};if(busy)CircularProgressIndicator(Modifier.size(18.dp),strokeWidth=2.dp)else Text(i.quantity.toString(),color=AxeCloudThemeTokens.Ink,fontWeight=FontWeight.Black);IconButton(plus,enabled=!busy){Icon(Icons.Outlined.AddCircleOutline,"Adicionar uma unidade",tint=color)}}}}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun InventoryEditor(item:InventoryItem?,saving:Boolean,error:String?,dismiss:()->Unit,save:(InventoryForm)->Unit){var f by rememberSaveable(item?.id){mutableStateOf(item?.let(InventoryForm::from)?:InventoryForm())};ModalBottomSheet(onDismissRequest=dismiss,containerColor=AxeCloudThemeTokens.Canvas){Column(Modifier.navigationBarsPadding().padding(horizontal=20.dp).padding(bottom=25.dp),verticalArrangement=Arrangement.spacedBy(11.dp)){Text(if(item==null)"Novo item" else "Editar estoque",color=AxeCloudThemeTokens.Ink,fontSize=24.sp,fontWeight=FontWeight.Black);Field(f.name,{f=f.copy(name=it)},"Item");Field(f.category,{f=f.copy(category=it)},"Categoria");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Field(f.quantity,{f=f.copy(quantity=it)},"Quantidade",Modifier.weight(1f));Field(f.minimum,{f=f.copy(minimum=it)},"Mínimo",Modifier.weight(1f))};error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Button({save(f)},Modifier.fillMaxWidth().height(52.dp),enabled=!saving,colors=ButtonDefaults.buttonColors(containerColor=Color(0xFF183744))){Text("Salvar no almoxarifado")}}}}
@Composable private fun Field(v:String,c:(String)->Unit,l:String,m:Modifier=Modifier.fillMaxWidth())=OutlinedTextField(v,c,m,label={Text(l)},singleLine=true,shape=RoundedCornerShape(15.dp))
@Composable private fun EmptyStock(low:Boolean)=Surface(shape=RoundedCornerShape(20.dp),color=Color.White,border=BorderStroke(1.dp,AxeCloudThemeTokens.Outline)){Column(Modifier.fillMaxWidth().padding(28.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Outlined.Inventory2,null,Modifier.size(36.dp),tint=Color(0xFF183744));Text(if(low)"Nenhuma reposição urgente" else "Almoxarifado vazio",color=AxeCloudThemeTokens.Ink,fontWeight=FontWeight.Black);Text(if(low)"O estoque está dentro dos níveis definidos." else "Cadastre os materiais usados pela casa.",color=AxeCloudThemeTokens.Muted,fontSize=11.sp)}}
